[package]
name = "shell-0"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "3.0.0"
is_executable = "1.0"
rustyline = "17.0.1"
