[package]
name = "shell-0"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
is_executable = "1.0"
users = "0.11.0"
libc = "0.2"
 exacl = "0.2" 